language: node_js
services: docker
sudo: required
node_js:
  - v12

before_install:
  - sudo /etc/init.d/postgresql stop
  # remove volume which create a permission denied issue
  - sed -i '\|logs/postgres|d' ./docker-compose.yml

stages:
  - name: Deploy Test

jobs:
  include:
    - stage: Deploy Test
      name: Deploy with start script
      script:
        - chmod +x start.sh && ./start.sh
        - curl -sSL https://git.io/gobackup | bash
        - gobackup -h
        - gobackup -v
        - sed -i 's/@@ACCESS_KEY_ID@@/'${ACCESS_KEY_ID}'/g; s/@@SECRET_ACCESS_KEY@@/'${ACCESS_KEY_ID}'/g' gobackup.yml
        - cat gobackup.yml
        - gobackup perform
        - echo 'pwd= ' && pwd
        - ls
        - ls /tmp/gobackup/

after_failure:
  - docker-compose config
  - docker-compose logs
